#!/bin/bash
sudo apt update
sudo apt install -y docker.io docker-compose
mkdir -p dockercom
cat <<EOF > dockercom/Windows_10_12GB_Ram_V2.yaml
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: 'https://download1528.mediafire.com/1e0s56wy8fvgxy4RBlfdJN62mJjtwuyA5SQ2ceweICamAq3RV9b4RXkXkSUSHwU2Uobppia8MTlUoFI90EC5ucf4cen7cxhm_0j1ZquqyqJcPFXDeAmSP8gPrGR5oFxdRMfl74gGB-fqhfXPVXUIhokpEmnXhzgeSDYQqOoM5y3mobXM/p9dzvddx0fqbehi/Win10PE.iso'
      USERNAME: 'Jor3a-Ti9niya'
      PASSWORD: 'admin@123'
      RAM_SIZE: '12G'
      CPU_CORES: '4'
      DISK_SIZE: '990G'
      DISK2_SIZE: '101G'
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    stop_grace_period: 2m
EOF

cd dockercom
sudo docker-compose -f Windows_10_12GB_Ram_V2.yaml up
